name: EasyAPI
main: com.letsdank.easyapi.main.Main
description: An Easy-to-Make API for developers
author: LetsDank
version: 0.2
load: STARTUP
permissions:
   eapi.command:
      default: op
commands:
   easyapi:
      description: Shows information to configure EasyAPI plugin
      aliases: eapi
      permission: eapi.command
      